version: "3.8"

services:
  redisearch:
    build: .
    container_name: redisearch-service
    ports:
      - "8090:8090"
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped